stages:
- name: Publish
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: bewerkdemarkten:${CICD_EXECUTION_SEQUENCE}
  envFrom:
    - sourceName:	bewerkdemarkten-frontend-subdir
      sourceKey: PUBLIC_URL
  env:
    PLUGIN_BUILD_ARGS_FROM_ENV: PUBLIC_URL

- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 45
branch:
  include:
  - master
notification: {}